### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by cellarosi** [Fantomas42/django-blog-zinnia#257]
I'm not able to understand why, but blog zinnia use a lot of RAM during executions.

I don't know where can I check really. Are there someone had same problem???

**Comment by fishi0x01** [comment]
I am having RAM issues too, but in my case also the CPU goes crazy. 
I recently opened an issue about it and in my case this seems to happen because of [some URLs in the entry's content](https://github.com/Fantomas42/django-blog-zinnia/issues/403). 
I also tried reducing the number of MaxClients etc. but this didn't solve it and my guess is that anyways the reason is a single worker, thus reducing any number of processes/threads in Apache will not have any effect on this issue.

Do you use URLs in your content? And if so, in case you remove them, does the issue still occur?

**Comment by Fantomas42** [comment]
Hello,

today I have just mae some new tests with Django 1.10, and with only the admin app, my instance use ~40Mo at startup and ~80Mo once a detail page has been rendered.
 
WIth a complete installation once the pages of the blog rendered even the admin pages, I reach ~86Mo so Zinnia does not create memory leaks, but Django like the RAM. 

I close the issue, unless new informations.

Regards
