### ISSUE TITLE
Using a custom Entry model causes any test that instantiates an Entry to hang open the database transaction using psql

### ISSUE THREAD

**Issue by stringfellow** [Fantomas42/django-blog-zinnia#306]
An example of this can be found here: 

https://github.com/stringfellow/django-blog-zinnia-database-test

**Comment by Fantomas42** [comment]
Hello today I have done some checks on this issue,

First of all, I can reproduce with the example project, but I cannot say it's not coming directly from Zinnia.

But I have found this issue related https://code.djangoproject.com/ticket/22420

So because this issue seems not coming from Zinnia, I will close the issue until more informations.
