### ISSUE TITLE
Tagging not working on Python 3

### ISSUE THREAD

**Issue by astrojuanlu** [Fantomas42/django-blog-zinnia#320]
Apparently Zinnia 0.14 was tagged but it doesn't work under Python 3 due to its dependency from django-tagging (see #281). If the solution is difficult, may I suggest stating that in the documentation?

**Comment by bittner** [comment]
@Fantomas42 You have the PR feature active in your [django-tagging repository](https://github.com/Fantomas42/django-tagging), but the Issues feature is deactivated.

I now have an issue I need to discuss, which may be related to Django 1.8.8, but I'm not sure. Can you activate the Issues feature, so that I can [open an issue](https://github.com/Fantomas42/django-tagging/issues/new) there?

**Comment by Fantomas42** [comment]
@bittner Yes I only accept PR on this repository.
I only maintains this repository on the compatibility side, so I do not fix issues.

But send me an email with details about your issue, and we will see together what can be done.

**Comment by bittner** [comment]
@Fantomas42 Alright, that's cool. I'm ashamed to say I found the problem myself. It was related to [cmsplugin-zinnia #issue 54](https://github.com/django-blog-zinnia/cmsplugin-zinnia/issues/54). :grimacing:
