### ISSUE TITLE
'View on site' throws this error: No entry found matching the query

### ISSUE THREAD

**Issue by Hiieu** [Fantomas42/django-blog-zinnia#395]
When I create new entry and click on 'View on site' I got this error:

```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/weblog/2015/02/05/Test/
No entry found matching the query
```

**Comment by Fantomas42** [comment]
If your entry is not published, the preview only works if you are superuser or if you are an author on the entry. Note your admin must be on the same domain than the front end, for making it work.

**Comment by Hiieu** [comment]
Why are you closing issue before OP's reply? 

I checked my entry as published and I am the superuser.

**Comment by Hiieu** [comment]
Why did you CLOSE this issue? You didn't give me a chance to reply.
My entry is published + I am on superuser and I still got the error. 

![IMG](http://i.imgur.com/EEUAuFT.png)

**Comment by Fantomas42** [comment]
I close the issue, because from the given information, I can only explain how it supposed to work. I cannot debug your installation, because my crystal ball is in maintenance.

Then you have a chance to reply, your reply is the perfect proof, and I have a chance to reopen the issue if I have more information.

But you came here, spamming the issue tracker, requiring support with the minimal effort from your side, whimpering when you don't have your expected answers... And questioning me with your CAPS about why I close the issue, this is the perfect introduction IMHO...

I want to say STOP.
Maybe I'm not kind or what-you-want, but you are not the first dude coming here and making this show. Here is for reporting issues, not for support. Then if you want support, review your presentation and the presentation of your problem.

Now I can only suggest you to try a manual debug with *pdb*, and reply on this issue if you find a bug in the code explaining this behavior.

Regards

**Comment by Hiieu** [comment]
Nevermind I solve this problem. Just uninstalled your app. Thank you very much. Have a good day.
