### ISSUE TITLE
Entries not filtered correctly on Entry.published.on_site

### ISSUE THREAD

**Issue by stefanw** [Fantomas42/django-blog-zinnia#420]
[These lines](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/managers.py#L54-L55) call the super-implementation of `get_queryset` and therefore do **not** call the method on the `EntryPublishedManager` class itself – thus skipping the check on `status` and start/end of publication, leading to the availability of unpublished entries when calling `Entry.published.on_site()`.

In the tests [this assert](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/tests/test_managers.py#L119) should return `1` as `entry_2` in the test is not published! There are some other test cases that begin to fail when fixing this bug.

As I discovered while tryin to fix it, this bug has some bigger consequences:

- the `on_site` call is used [in `EntryDetail`](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/views/entries.py#L26).
- a correct checking of publication status in `on_site` would mean that non-published objects do not appear in the queryset anymore
- this breaks the [EntryPreviewMixin](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/views/mixins/entry_preview.py) which expects to check the resulting object individually (however, no unpublished object will ever get there).

This needs some design decisions, so I opened an issue rather than a PR.

**Comment by Fantomas42** [comment]
Hello, the ``on_site`` method is perfectly fine is state.

Like his name say, it focus only on entries created for a site, not the entries published on the site, otherwise the method would be called ``published_on_site``. :)

This manager method is used to preview the entries posted on the site but not yet published. And in the case of a mult-sites project a filtering is done, to avoid seeing entries not intended to be visible on a specific site.

Regards

**Comment by stefanw** [comment]
Well, then the name `Entry.published.on_site` is highly misleading! When I use a manager called `published`, I expect it to give me only published entries, no matter what method I call on it later!

I found that even though `Entry.is_visible` returns `false` (and the entry is therefore marked as invisible in the admin), non logged-in users can access the entry by URL. That's because `is_visible` also checks the start/end publication date which **does not happen** in the [EntryPreviewMixin](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/views/mixins/entry_preview.py#L21-L22) where it just checks for publication status.

I inferred that the `published` manager was to blame here, but if you say it's not, then `EntryPreviewMixin` needs another check for publication date.

**Comment by Fantomas42** [comment]
Checks needs to be done

**Comment by Fantomas42** [comment]
You are right, a better check could be done.

About the name of `published.on_site`, your are right it can be misleading, but because it does not override a standard method, it's not a real problem IMO. 
I could change this by subclassing the default manager and doing the same thing, but it's a waste of time and code. 
And I love this idiom, `Entry.published.on_site` sounds Pythonic to me, even if the behaviour is not clear for everyone.

**Comment by stefanw** [comment]
Awesome, thanks!
