### ISSUE TITLE
test error with simple-captcha

### ISSUE THREAD

**Issue by heibanke** [Fantomas42/django-blog-zinnia#445]
thanks for your app, it is very userful for me.

when i use django-simple-captcha with zinnia, i found the question and pull one issue to captcha.
https://github.com/mbi/django-simple-captcha/issues/93

but i don't know it should be the captcha problem or zinnia problem, would you give me some suggestion to solve this issue?

**Comment by Fantomas42** [comment]
Hello,

like explained in https://github.com/mbi/django-simple-captcha/issues/93, the URLconf is overridden within the tests of simple-captcha, the URLs of Zinnia are not included.

But why the tests need to reverse a Zinnia urls ? 
Because the tests in simple-captcha are failing, so the Django test client try to render the 500.html page bundled by default in Zinnia.

Fix the tests of simple-captcha, and it's okay.

But the issue is not really coming from Zinnia.

Regards

**Comment by heibanke** [comment]
ok，Thanks for your reply and your Zinnia, i like it and have used it for one year.
