### ISSUE TITLE
Improve Tutorial: "Customize Zinnia’s look and feel"

### ISSUE THREAD

**Issue by bartmika** [Fantomas42/django-blog-zinnia#449]
Salutations,

I have followed your instructions and I have successfully got everything working until this section. My site looks literally one-to-one to the demo site: http://demo.django-blog-zinnia.com/blog/.

I have spent a great deal of time in this section and to no-avail: I was unable to figure out how to change the look look 'n' feel.

Would it be possible if you re-write this section and/or write a more detailed tutorial? Again this section gives me immense difficulty in figuring out.

Thank you kindly,
-Bart

**Comment by Fantomas42** [comment]
Hello,

I agree with the fact that the documentation is not really clear for a newcomer.

But I don't see what to re-write, because I don't see what you don't understand precisely...

Then note that English is not my maternal language, so rewriting this part of the documentation for more clarity, would be difficult for me.

Regards

**Comment by bartmika** [comment]
Hi @Fantomas42,

Understood - my problem is:

(1) Where do I modify the CSS / JS of default template?
(2) Where do I modify the HTML pages of the default template?

In essance I have a custom bootstrap theme I want to replace the default Zinnia's template. How do I go about doing that?

Thanks!
