### ISSUE TITLE
TypeError "sequence index must be integer, not 'slice'" in 0.16

### ISSUE THREAD

**Issue by NazarTopolsky** [Fantomas42/django-blog-zinnia#478]
While it has been addressed in <a href="https://github.com/Fantomas42/django-blog-zinnia/pull/465">#465</a>, latest version in master (0.16) still has this bug, making app unusable with Django 1.9 despite what documentation claims. While one can simply install zinnia from development branch, I wouldn't feel safe using it in production.
Same goes for the package on PyPi.

**Comment by Fantomas42** [comment]
Hello,

I don't see your problem, or the solution.... 

First of all, the stable release 0.16, don't say it's compatible with 1.9...

http://docs.django-blog-zinnia.com/en/stable/getting-started/install.html 

Secondly

> While one can simply install zinnia from development branch, I wouldn't feel safe using it in production.

Oh ! And why ? Where is the difference ??? Just because one commit has been tagged with Git ?

Either you wait for the new stable release, or you keep your fears and use a non-tagged release.

I don't know what do you expect from me by reporting an already know and fixed issue...

Regards

**Comment by NazarTopolsky** [comment]
Then how about this?
http://django-blog-zinnia.readthedocs.io/en/develop/getting-started/install.html
Docs suggest using "pip install django-blog-zinnia" (which yields 0.16), and claim "Django >= 1.9,<1.10" at the same time. Maybe I should really open issue concerning docs then, idk.

>> While one can simply install zinnia from development branch, I wouldn't feel safe using it in production.

>Oh ! And why ? Where is the difference ??? Just because one commit has been tagged with Git ?

Well, maybe it's just me, but "develop" branch is usually called this way, because code is "in development", which suggests that some features are experimental/not stable yet. However, if you treat "develop" branch as responsibly, as you do "master", I take that back.

**Comment by Fantomas42** [comment]
The link that you pasted, refers to the develop version of Zinnia.
The title of the page specify "Django Blog Zinnia 0.17.dev0 documentation"
The pip install part, says that this concern stable version.

No problems for me, just use the documentation related to your installed version of Zinnia.

About the "develop" branch, only completed features are merged into it, so it should be stable, thanks to git flow.

Regards
