### ISSUE TITLE
Can't migrate for a custom Entry model

### ISSUE THREAD

**Issue by zmrenwu** [Fantomas42/django-blog-zinnia#491]
I add a custom Entry model in my app: 

```
myapp/models.py

from zinnia.models_bases.entry import AbstractEntry

class BlogEntry(AbstractEntry):
    class Meta(AbstractEntry.Meta):
        abstract = True
```

I set `MIGRATION_MODULES` for zinnia like:

```
ZINNIA_ENTRY_BASE_MODEL = 'myapp.models.BlogEntry'
MIGRATION_MODULES = {
    'zinnia': 'myapp.migrations',
}
```

Then I run makemigrations command and it generate the initial migration file. But when I run migrate, it complained `ValueError: Related model 'zinnia.Category' cannot be resolved`

I read the documentation about how to custom entry model, it says:

> It’s recommended that the new initial migration represents the default Entry schema provided by Zinnia, because after that, you just have to write a new migration for reflecting your changes, and you just alter your database schema with the migrate command.

I also copy the initial migration file from zinnia.migrations package, but didn't work too.

What should I do according to the docs? I search this problem in google and stackoverflow but didn't find useful informations. Thanks for your help!

**Comment by divick** [comment]
I too am facing the same issue. I see that even with mentioning the migration_modules, the migrations present in the zinnia installation conflict with the migration generated in your app and hence this issue. I see two ways to fix it.

1. Do no use the migration_modules setting and the changes will be done in the zinnia package itself. 

2. Remove the migrations from the zinnia package and enable migration_modules for your app and all blog related tables will be generated in your app (myapp).

**Comment by Fantomas42** [comment]
Hello,

@divick this is not the right way to do.

@zmrenwu I will reproduce the case and see what to do.

Best regards

**Comment by divick** [comment]
@Fantomas42 Yeah I know both the suggested solutions are ugly but I couldn't figure out a way to have half migrations in zinnia package and half in a your app. The ownership of models has to be take care of either by zinnia itself or your own package. Am I missing something over here?

**Comment by Fantomas42** [comment]
Hello all,

I have made some tests based on your case, and for me everything works fine.
But here a few canveats.

- When changing the MIGRATIONS_MODULES, don't put the migrations for zinnia, into the directory 'migrations', can it will interfere with the current migrations of your app. Instead 'zinnia_migrations' is better and explicit.

- Before creating the migration for your new field, you should create a new initial migration for zinnia, that will reflect the state of Zinnia before your changes. 

- Then define ZINNIA_ENTRY_BASE_MODEL and create a your migration.

Note that applying this workflow, even if you update your installation on Zinnia, if new fields are provided, you just have to make a makemigrations, and you are OK.

Note if you have existing datas, after the creation of the initial migration, be sure to reset the migration state to Zinnia at 0001.

Regards

**Comment by divick** [comment]
@Fantomas42 Thanks for your reply but the procedure you listed does not work. So here is what I did.

1. I first added zinnia to installed_apps. At this point running python manage.py showmigrations shows:
zinnia
 [X] 0001_initial
 [X] 0002_lead_paragraph_and_image_caption
 [X] 0003_publication_date
 [X] 0004_on_delete_arg

which is correct as these are the migrations in the zinnia installed location.

2. I then extended the EntryModel (actually created a new model like EntryModel with importing the same set of mixins that EntryModel does).

3. I defined ZINNIA_ENTRY_BASE_MODEL = 'blog.models.VideoEntry' in my settings, where blog is the app where I have extended/created the EntryModel.

4. At this point if I generate any new migrations they will go by default in zinnia installation unless I define MIGRATION_MODULES. So I define this to:

```
MIGRATION_MODULES = {
    'zinnia': 'blog.migrations',
}
```
At this point when I run showmigrations I see that it show there are no migrations for either my 'blog' app or 'zinnia' which is expected as the location of migrations is blog/migrations.

If I run makemigrations now it first creates an initial migration for zinnia and then running the makemigrations again it creates another migration for blog as seen below:
```

Migrations for 'zinnia':
  blog/migrations/0001_initial.py:
    - Create model Category
    - Create model Entry
    - Create proxy model Author
    - Add field authors to entry
    - Add field categories to entry
    - Add field related to entry
    - Add field sites to entry

Migrations for 'blog':
  blog/migrations/0002_auto_20170406_0654.py:
    - Remove field parent from category
    - Remove field authors from entry
    - Remove field categories from entry
    - Remove field related from entry
    - Remove field sites from entry
    - Delete model Author
    - Delete model Category
    - Delete model Entry
```

Now since both are leaf migrations in the same directory, when running migrate, it leads to django error that there are conflicting migrations 0001 and 0002. 

If I change the migrations_module to as you suggest:

```
MIGRATION_MODULES = {
    'zinnia': 'blog.zinnia_migrations',
}
```
so that migrations for zinnia are stored separately for zinnia and blog, then it fails to detect any changes in any model and does not generate any migration whatsoever.

Overall I think this is quite convoluted way of handling this issue. I am wondering what is the standard way it is handled in reusable apps. A good example is django_allauth package which utilizes django.contrib.auth package and the user can still extend the django.contrib.auth.models.User model without defining MIGRATION_MODULES for the django.contrib.auth app. I guess something like that can be done here too.

**Comment by divick** [comment]
I guess using https://github.com/wq/django-swappable-models for allowing the users of django-zinnia to override the default implementation would be better.
