### ISSUE TITLE
AttributeError at /admin/zinnia/category/add/ 'TreeForeignKey' object has no attribute 'remote_field'

### ISSUE THREAD

**Issue by shamyla** [Fantomas42/django-blog-zinnia#495]
# Actual behavior

AttributeError at /admin/zinnia/category/add/
'TreeForeignKey' object has no attribute 'remote_field'
# Expected behavior
Category should be added exactly as it should had.

# Steps to reproduce the issue

  1.Install django==1.8/9/10 (Tried all versions, current version==1.9
  2.After makemigrations/migrate when runserver si executed, It won't let me add a category.
  3. Updated django-mptt and checked in detail if there is something I am doing wrong or any mismatched version but everything is perfect to my knowledge.

# Specifications

 - Zinnia version:0.18.1
 - Django version:1.9
 - Python version:2.7.11
 - Operating system:Windows

# Disclaimer
I have read all the documentation and double checked the settings needed for django-blog-zinnia. Following is the check list.

 - [x ] I have read the guidelines for contributing linked to above.
 - [x ] I have checked for duplicate issues.
 - [x ] This is not a support request.

Regards,
Shamaila

**Comment by wyx2000** [comment]
cannot get 0.18.1 running, simple too many issues, 
On admin side, I got the same 'TreeForeignKey' object has no attribute 'remote_field' issue
On client side, I got 'zinnia_loop_template' received too many positional arguments

**Comment by esplinr** [comment]
I only got these errors when running on Django below 1.10.

See http://docs.django-blog-zinnia.com/en/develop/notes/compatibility.html

**Comment by Fantomas42** [comment]
Hello,

@shamyla like @esplinr said, this error should only happen with version inferior to django 1.9, which is the version introducing the remote_field attribute.

Once said, this issue is coming from your version of Django, because only Django generate this attribute on the fields.

@wyx2000 please don't mix the issues, be positive and constructive. I suggest you to adapt your customized templates for your client side issue.

Regards
