### ISSUE TITLE
Unabled customizing zinnia blog

### ISSUE THREAD

**Issue by harshaddevale-tudip** [Fantomas42/django-blog-zinnia#500]
# Actual behavior
When I copy both  zinnia folder from git, my application producing following error:
Invalid block tag: 'zinnia_loop_template', expected 'empty' or 'endfor'

# Expected behavior
- Blog page should contain my header, footer and added blog post's.

# Steps to reproduce the issue

  1. Install django-blog-zinnia==0.15.2 using 'pip' command.
  2. Copy zinnia/base.html from git to existing django project's templates directory.
  3. Extend zinnia/base.html by your project's base.html

# Specifications
 - Zinnia version: 0.15.2
 - Django version: 1.7.1
 - Python version: 2.7.6
 - Operating system: Ubuntu-14.04

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [X ] I have read the guidelines for contributing linked to above.
 - [ X] I have checked for duplicate issues.
 - [ X] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

you cannot copy the templates from the git repository, because is too advanced compared to your version v0.15.2. 

The zinnia_loop_template templatetag was introduced in v0.16, so yo have at least to adapt the copied templates, or copy the templates directly from your installed version.

Regards
