### ISSUE TITLE
Linkbacks and trackbacks still open

### ISSUE THREAD

**Issue by iustitia** [Fantomas42/django-blog-zinnia#504]
# Actual behavior
I read the tip on RTD about setting and those should close linkbacks and trackbacks on each post:
ZINNIA_AUTO_CLOSE_TRACKBACKS_AFTER = 0
ZINNIA_AUTO_CLOSE_PINGBACKS_AFTER = 0

However after the post publication, they are both still open.

# Expected behavior
Trackback and linkback should be closed.

# Steps to reproduce the issue

  1. Write new post and publish.
  2. Check the settings in admin panel.

# Specifications

 - Zinnia version: 1.18.1
 - Django version: 1.10
 - Python version: 3.5
 - Operating system: FreeBSD

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

these settings does not change the values in the admin interface, only the manner to compute if the pingbacks or the trackbacks are still open several days after the publication of the entry.

Regards

**Comment by iustitia** [comment]
That would mean that with the values I set pingbacks and trackbacks are closed after publishing a note. But they are not closed, unless I uncheck them in admin interface. Is that the right behaviour or am I missing something?

**Comment by Fantomas42** [comment]
If you set these values to 0, even if the check-boxes are checked, the pingbacks and trackbacks will never be opened.

The check-boxes are useful if you set theses values with a number superior to 0, because with these you can open or close the trackback/pingback individually for each entries.

If I resume: in a certain manner the check-boxes are for individual control, but the settings are for global control.

Regards
